"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/sections/navbar'
import { cn } from "@/lib/utils"
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" > 
      <body className={cn("bg-neutral-50", inter.className )}>
        <Navbar/>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
